<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="assets/style.css">
    <title>Document</title>
</head>

<body>
    <header>
        <h1>
            <img src="https://www.wildcodeschool.com/assets/logo_main-e4f3f744c8e717f1b7df3858dce55a86c63d4766d5d9a7f454250145f097c2fe.png" alt="Wild Code School logo" />
            Les Argonautes
        </h1>
    </header>

    <!-- Main section -->
    <main>
        <div class="container">
            <form action="editMembre.php" method="POST">
                <input type="hidden"  id="id"name="id" value="<?= $MembreId['id'] ?>">
                <div class="form-group col-4">
                </div>
                <div class="form-group col-8">
                    <label for="memebre">Nom :</label>
                    <input type="text" class="form-control" id="membre" name="membre" maxlength="30" value="<?= $MembreId['membre'] ?>">
                </div>
                <button type="submit" class="btn btn-primary">Enregistrer</button>
        </div>
        <button type="submit" class="btn btn-primary mt-2" value="Retour" onclick="history.go(-1)">Retour</button>
        </form>
        </div>
    </main>