<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="stylesheet" href="assets/style.css">
  <title>Document</title>
</head>

<body>
  <header>
    <h1>
      <img src="https://www.wildcodeschool.com/assets/logo_main-e4f3f744c8e717f1b7df3858dce55a86c63d4766d5d9a7f454250145f097c2fe.png" alt="Wild Code School logo" />
      Les Argonautes
    </h1>
  </header>

  <!-- Main section -->
  <main>

    <!-- New member form -->
    <h2>Ajouter un(e) Argonaute</h2>
    <form action="index.php" method="POST" enctype="multipart/form-data">
      <div class="form-group col-8 ">
        <label for="membre">Nom :</label>
        <input type="text" class="form-control " id="membre" name="membre" maxlength="50">
      </div>
      <div class="form-group col-8">
        <button type="submit" class="btn btn-primary mt-2">Enregistrer</button>
      </div>

    </form>

    <!-- Member list -->
    <h2>Membres de l'équipage</h2>
    <div class="container">
      <div class="row">
        <?php foreach ($equipage as $liste) : ?>
          <div class="card m-3" style="width: 18rem;">
            <div class="card-body">
              <h5 class="card-title"><?= $liste['membre'] ?></h5>
              <a href="showMembre.php?id=<?= $liste['id'] ?>"><i class="fa-solid fa-eye"></i></a>
              <a href="editMembre.php?id=<?= $liste['id'] ?>"><i class="fa-solid fa-pen-to-square"></i></a>
              <a href="deletMembre.php?id=<?= $liste['id'] ?>"><i class="fa-solid fa-circle-minus"></i></a>
            </div>
          </div>
        <?php endforeach; ?>
      </div>
    </div>
    </table>
  </main>



  <script src="/assets/script.js"></script>
</body>
<footer>
  <p>Réalisé par Jason en Anthestérion de l'an 515 avant JC</p>
</footer>

</html>